Repository 93HSpring/CoffeeReview, pull requests merged in 2020-09, with the labels that each got.

#13 ADD: getBoard comment 등록 기능 추가
  src/main/java/com/hspring/coffeereview/view/board/CommentController.java
  src/main/webapp/getBoard.jsp
Labels: enhancement

#20 Refactor: getBoardList.jsp, getBoard.jsp 파트별 분리
  src/main/java/com/hspring/coffeereview/view/board/BoardController.java
  src/main/resources/applicationContext.xml
  src/main/webapp/WEB-INF/include/control_sidebar.jsp
  src/main/webapp/WEB-INF/include/getBoard_plugin_js.jsp
  src/main/webapp/WEB-INF/include/head.jsp
  src/main/webapp/WEB-INF/include/main_footer.jsp
  src/main/webapp/WEB-INF/include/main_sidebar.jsp
  src/main/webapp/WEB-INF/include/navbar.jsp
  src/main/webapp/WEB-INF/include/plugin_js.jsp
  src/main/webapp/getBoard.jsp
  src/main/webapp/getBoardList.jsp
  target/classes/applicationContext.xml
  target/classes/com/hspring/coffeereview/view/board/BoardController.class
  target/m2e-wtp/web-resources/META-INF/maven/com.hspring/coffeereview/pom.properties
Labels: refactor

#21 Add: getBoardList 별점 출력 기능 보완
  src/main/java/com/hspring/coffeereview/view/board/BoardController.java
  target/classes/com/hspring/coffeereview/view/board/BoardController.class
Labels: enhancement

#22 Feature: userInfo 조회 및 수정 탭 보완
  src/main/java/com/hspring/coffeereview/biz/user/UserService.java
  src/main/java/com/hspring/coffeereview/biz/user/UserVO.java
  src/main/java/com/hspring/coffeereview/biz/user/impl/UserDAO.java
  src/main/java/com/hspring/coffeereview/biz/user/impl/UserServiceImpl.java
  src/main/java/com/hspring/coffeereview/view/user/LoginController.java
  src/main/java/com/hspring/coffeereview/view/user/UserController.java
  src/main/webapp/index.jsp
  src/main/webapp/login.jsp
  src/main/webapp/register.jsp
  src/main/webapp/signup.jsp
  src/main/webapp/signupSuccess.jsp
  src/main/webapp/userInfo.jsp
Labels: enhancement

#24 set: users 테이블 column명 수정
  src/main/java/com/hspring/coffeereview/biz/user/UserService.java
  src/main/java/com/hspring/coffeereview/biz/user/UserVO.java
  src/main/java/com/hspring/coffeereview/biz/user/impl/UserDAO.java
  src/main/java/com/hspring/coffeereview/biz/user/impl/UserServiceImpl.java
  src/main/java/com/hspring/coffeereview/view/user/LoginController.java
  src/main/java/com/hspring/coffeereview/view/user/UserController.java
  src/main/webapp/register.jsp
  src/main/webapp/userInfo.jsp
  target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  target/m2e-wtp/web-resources/META-INF/maven/com.hspring/coffeereview/pom.properties
Labels: set
